User.create(first_name: "Lee-roy", last_name: "Jenkins", origin_address: "fence.gross.bats", password: "pass", username: "user1" )
User.create(first_name: "Jenna", last_name: "Taylor", origin_address: "powers.dsting.making", password: "pass", username: "user2" )
User.create(first_name: "Peter", last_name: "Parker", origin_address: "confined.squabbles.lance", password: "pass", username: "user3" )
User.create(first_name: "Mike", last_name: "Jones", origin_address: "classed.dolphin.multiples", password: "pass", username: "user4" )
User.create(first_name: "Kate", last_name: "Blanchet", origin_address: "sweated.braved.untruth", password: "pass", username: "user5" )
User.create(first_name: "Niki", last_name: "N", origin_address: "feared.later.bright", password: "pass", username: "ned-el-ch" )
User.create(first_name: "Dan", last_name: "Khaneman", origin_address: "salad.likening.sprinting", password: "pass", username: "danK" )
User.create(first_name: "Ali", last_name: "Express", origin_address: "pylon.video.reputable", password: "pass", username: "chineseAmazon" )
User.create(first_name: "Molly", last_name: "Wolly", origin_address: "melts.galloped.gulped", password: "pass", username: "lyttaf" )
User.create(first_name: "Jeff", last_name: "Base", origin_address: "test.dislodge.offshore", password: "pass", username: "terminator" )

Destination.create(name: "Kelly Schitz", destination_address: "cages.push.galaxy")
Destination.create(name: "Martin Katz", destination_address: "toxic.removing.myths")
Destination.create(name: "Simon Slough", destination_address: "swerving.fancy.rectangular")
Destination.create(name: "Bobby Banjo", destination_address: "eating.skirting.boot")
Destination.create(name: "Bobby Shmurda", destination_address: "under.tower.bridge")

Delivery.create(user_id: 3, destination_id: 1, status: "delivered", description: "non-radioactive spiders", distance: 145.53, cost: 1455.30, speed: "lightning")
Delivery.create(user_id: 5, destination_id: 1, status: "in transit", description: "bottles of liquor", distance: 14.53, cost: 76, speed: "express")
Delivery.create(user_id: 1, destination_id: 3, status: "delivered", description: "laptop a keyboard keys", distance: 15.53, cost: 75, speed: "express")
Delivery.create(user_id: 3, destination_id: 4, status: "in transit", description: "monitors", distance: 45.53, cost: 200, speed: "express")
Delivery.create(user_id: 6, destination_id: 5, status: "delivered", description: "not body parts", distance: 5.53, cost: 55.30, speed: "lightning")
Delivery.create(user_id: 7, destination_id: 4, status: "in transit", description: "defo not steroids", distance: 12, cost: 120, speed: "lightning")
Delivery.create(user_id: 8, destination_id: 5, status: "delivered", description: "a bunch of Sergio clones", distance: 53.53, cost: 53.53, speed: "standard")
Delivery.create(user_id: 2, destination_id: 2, status: "in transit", description: "secrets", distance: 95.2, cost: 95.2, speed: "standard")
Delivery.create(user_id: 9, destination_id: 2, status: "in transit", description: "the meaning to life jk lol", distance: 51.6, cost: 51.6, speed: "standard")
Delivery.create(user_id: 10, destination_id: 2, status: "in transit", description: "cream cheese donut", distance: 9000.2, cost: 90002.0, speed: "lightning")