User.create(first_name: "Lee-roy", last_name: "Jenkins", origin_address: "fence.gross.bats" )
User.create(first_name: "Jenna", last_name: "Taylor", origin_address: "powers.dsting.making" )
User.create(first_name: "Peter", last_name: "Parker", origin_address: "confined.squabbles.lance" )
User.create(first_name: "Mike", last_name: "Jones", origin_address: "classed.dolphin.multiples" )
User.create(first_name: "Kate", last_name: "Blanchet", origin_address: "sweated.braved.untruth" )
User.create(first_name: "Gert", last_name: "Grabber", origin_address: "feared.later.bright" )
User.create(first_name: "Pyros", last_name: "Dimas", origin_address: "salad.likening.sprinting" )
User.create(first_name: "Ali", last_name: "Roberts", origin_address: "pylon.video.reputable" )
User.create(first_name: "Molly", last_name: "Kendle", origin_address: "melts.galloped.gulped" )
User.create(first_name: "Kevin", last_name: "Bass", origin_address: "test.dislodge.offshore" )

Destination.create(name: "Kelly Schitz", destination_address: "cages.push.galaxy")
Destination.create(name: "Martin Katz", destination_address: "toxic.removing.myths")
Destination.create(name: "Simon Slough", destination_address: "swerving.fancy.rectangular")
Destination.create(name: "Bobby Banjo", destination_address: "eating.skirting.boot")
Destination.create(name: "Bobby Shmurda", destination_address: "under.tower.bridge")