User.create(first_name: "Lee-roy", last_name: "Jenkins", origin_address: "fence.gross.bats", password: "pass", username: "user1" )
User.create(first_name: "Jenna", last_name: "Taylor", origin_address: "powers.dsting.making", password: "pass", username: "user2" )
User.create(first_name: "Peter", last_name: "Parker", origin_address: "confined.squabbles.lance", password: "pass", username: "user3" )
User.create(first_name: "Mike", last_name: "Jones", origin_address: "classed.dolphin.multiples", password: "pass", username: "user4" )
User.create(first_name: "Kate", last_name: "Blanchet", origin_address: "sweated.braved.untruth", password: "pass", username: "user5" )
User.create(first_name: "Gert", last_name: "Grabber", origin_address: "feared.later.bright", password: "pass", username: "user6" )
User.create(first_name: "Pyros", last_name: "Dimas", origin_address: "salad.likening.sprinting", password: "pass", username: "user7" )
User.create(first_name: "Ali", last_name: "Roberts", origin_address: "pylon.video.reputable", password: "pass", username: "user8" )
User.create(first_name: "Molly", last_name: "Kendle", origin_address: "melts.galloped.gulped", password: "pass", username: "user9" )
User.create(first_name: "Kevin", last_name: "Bass", origin_address: "test.dislodge.offshore", password: "pass", username: "user10" )

Destination.create(name: "Kelly Schitz", destination_address: "cages.push.galaxy")
Destination.create(name: "Martin Katz", destination_address: "toxic.removing.myths")
Destination.create(name: "Simon Slough", destination_address: "swerving.fancy.rectangular")
Destination.create(name: "Bobby Banjo", destination_address: "eating.skirting.boot")